#!/bin/bash

# -------------------------
#
#   Operation Jump Script 
#
# -------------------------

# Ansible Hosts file Path
Hosts_PATH=""             # If equal "" , Default value is "/etc/ansible/hosts"

# "Host name" variable in Hosts file , Warnning : It must be set in $2 for AWK tools to carry it
Hosts_NAME=""       # If equal "" , Default value is HostName

# whether if Show Details of Menu , values 1 means that show more details of menu , else none.
Details_Enable=1

# Watting Time for heiheihei
Watting_TIME=0      # !!! Life is hard , but you are sweet .

[ "${Hosts_PATH}" == "" ] && Hosts_PATH=/etc/ansible/hosts
[ "${Hosts_NAME}" == "" ] && Hosts_NAME=HostName
[ ! -e $Hosts_PATH ] && echo "Error:$Hosts_PATH is not exist"
cat $Hosts_PATH |egrep "^[0-9]" > /tmp/hosts

# Load Ansible Hosts file Information
Count=0
while read line
do
    Ip_Arrary[$Count]=$(echo $line|awk '{print $1}')
    HostName_Arrary[$Count]=$(echo $line|awk '{print $2}'|cut -d= -f2|sed 's/"//g')
    let Count=$Count+1
done < /tmp/hosts

# Menu
Menu(){
if [ $1 -eq 1 ];then
  for((k=0;k<${Count};k=k+1))
  do
      printf "%-5s %-17s %-10s\n" [$k] ${HostName_Arrary[$k]} ${Ip_Arrary[$k]}
  done
else
  for((k=0;k<${Count};k=k+2))
  do
      let Right=$k+1
      if [ $Right -lt $Count ];then
        printf "%-5s %-15s %-5s %-15s\n" [$k] ${HostName_Arrary[$k]} [$Right] ${HostName_Arrary[$Right]}
      else
        printf "%-5s %-10s\n" [$k] ${HostName_Arrary[$k]}
      fi
  done
fi
}

# Main
# ---
if [ $# -eq 0 ];then

echo -e "\e[91m _   _         _____             _   _         ____  _\e[0m"      
echo -e "\e[91m| \ | | ___   |__  /   _  ___   | \ | | ___   |  _ \(_) ___\e[0m" 
echo -e "\e[91m|  \| |/ _ \    / / | | |/ _ \  |  \| |/ _ \  | | | | |/ _ \ \e[0m"
echo -e "\e[91m| |\  | (_) |  / /| |_| | (_) | | |\  | (_) | | |_| | |  __/\e[0m"
echo -e "\e[91m|_| \_|\___/  /____\__,_|\___/  |_| \_|\___/  |____/|_|\___|
\e[0m"

for((i=${Watting_TIME};i>0;i--))
do 
   echo -ne "\rYou are allowed to opera after $i seconds"
   sleep 1
   [ $i -eq 1 ] && echo
done

Menu $Details_Enable
while true
do
  read -p "Please chose the number of Hosts to ssh :" Num
  expr $Num "+" 10 > /dev/null 2>&1
  [ $? -ne 0 ] && echo "Input Error!" && continue
  if [ $Num -ge 0 -a $Num -lt $Count ];then
     ssh ${Ip_Arrary[$Num]}
     if [ $? -eq 0 ];then
        Menu $Details_Enable
     else
        continue
     fi
  else
     echo "Input Error!"       
  fi
done

# ---
elif [ $# -eq 1 ];then
  expr $1 "+" 10 > /dev/null 2>&1
  [ $? -ne 0 ] && echo "Input Error!" && exit
  if [ $1 -ge 0 -a $1 -lt $Count ];then
     ssh ${Ip_Arrary[$1]}
  else
     echo "Input Error!"
  fi

# ---
else
  echo "Input Error!" && exit
fi
